use serde::Deserialize;
use std::collections::HashMap;
use std::io::Write;
use std::path::{Path, PathBuf};

// Pinned commit of https://github.com/pawel-0/xdg-unused-data
const XDG_DATA_REPO: &str = "https://github.com/pawel-0/xdg-unused-data";
const XDG_DATA_SHA: &str = "main"; // Use branch name; bump to a SHA for reproducibility.

#[derive(Debug, Deserialize)]
struct XdgJson {
    name: String,
    #[serde(default)]
    executables: Vec<String>,
    #[serde(default)]
    locations: Vec<XdgLocation>,
}

#[derive(Debug, Deserialize)]
struct XdgLocation {
    file: String,
}

fn main() {
    let out_dir = PathBuf::from(std::env::var("OUT_DIR").unwrap());
    let data_dir = out_dir.join("xdg-data");
    let manifest_dir = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").unwrap());

    // Re-run if vendored data or build script change.
    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed=data/apps");

    let clone_ok = ensure_cloned(&data_dir);

    // Load upstream entries.
    let mut entries = if clone_ok {
        parse_entries(&data_dir.join("applications"))
    } else {
        eprintln!("cargo:warning=xdg-unused-data clone failed — building with empty db");
        Vec::new()
    };

    // Load vendored entries from data/apps/ — these supplement/override upstream.
    let vendored_dir = manifest_dir.join("data").join("apps");
    if vendored_dir.exists() {
        let mut vendored = parse_entries(&vendored_dir);
        entries.append(&mut vendored);
    }

    generate_phf(&out_dir, &entries);
}

fn ensure_cloned(data_dir: &Path) -> bool {
    if data_dir.join("applications").exists() {
        // Already cloned — no need to re-clone.
        return true;
    }

    eprintln!("Cloning xdg-unused-data ...");
    let parent = data_dir.parent().unwrap();
    let dir_name = data_dir.file_name().unwrap();

    let status = std::process::Command::new("git")
        .args([
            "clone",
            "--depth",
            "1",
            "--branch",
            XDG_DATA_SHA,
            XDG_DATA_REPO,
            &data_dir.to_string_lossy(),
        ])
        .current_dir(parent)
        .status();

    match status {
        Ok(s) if s.success() => {
            eprintln!("Cloned xdg-unused-data to {}", data_dir.display());
            true
        }
        Ok(s) => {
            eprintln!(
                "cargo:warning=git clone failed with status {s} for {}",
                dir_name.to_string_lossy()
            );
            false
        }
        Err(e) => {
            eprintln!("cargo:warning=git clone error: {e}");
            false
        }
    }
}

fn parse_entries(apps_dir: &Path) -> Vec<(String, XdgJson)> {
    let read_dir = match std::fs::read_dir(apps_dir) {
        Ok(d) => d,
        Err(e) => {
            eprintln!("cargo:warning=cannot read applications dir: {e}");
            return Vec::new();
        }
    };

    let mut entries = Vec::new();
    for item in read_dir.flatten() {
        let path = item.path();
        if path.extension().and_then(|e| e.to_str()) != Some("json") {
            continue;
        }
        let content = match std::fs::read_to_string(&path) {
            Ok(c) => c,
            Err(e) => {
                eprintln!("cargo:warning=skipping {}: {e}", path.display());
                continue;
            }
        };
        match serde_json::from_str::<XdgJson>(&content) {
            Ok(entry) => {
                let key = entry.name.to_lowercase();
                entries.push((key, entry));
            }
            Err(e) => {
                eprintln!("cargo:warning=parse error in {}: {e}", path.display());
            }
        }
    }

    entries
}

fn generate_phf(out_dir: &Path, entries: &[(String, XdgJson)]) {
    let dest = out_dir.join("xdg_db.rs");
    let mut file = std::fs::File::create(&dest).expect("creating xdg_db.rs");

    // Emit the static data structs.
    writeln!(
        file,
        "// Auto-generated by build.rs — do not edit.\n\
         #[derive(Debug)]\n\
         pub struct XdgEntry {{\n\
         \tpub name: &'static str,\n\
         \tpub executables: &'static [&'static str],\n\
         \tpub locations: &'static [XdgEntryLocation],\n\
         }}\n\
         #[derive(Debug)]\n\
         pub struct XdgEntryLocation {{\n\
         \tpub path: &'static str,\n\
         }}\n"
    )
    .unwrap();

    // Build unique key list (lowercase name), deduplicating.
    let mut seen: HashMap<String, usize> = HashMap::new();
    let mut deduped: Vec<(String, &XdgJson)> = Vec::new();

    for (key, entry) in entries {
        if !seen.contains_key(key) {
            seen.insert(key.clone(), deduped.len());
            deduped.push((key.clone(), entry));
        }
    }

    // Emit the PHF map.
    let mut map_builder = phf_codegen::Map::new();

    for (key, entry) in &deduped {
        // Emit a static for each entry's exe list and location list.
        let safe_key = key.replace(|c: char| !c.is_alphanumeric(), "_");

        let exe_ident = format!("XDB_EXES_{}", safe_key.to_uppercase());
        let loc_ident = format!("XDB_LOCS_{}", safe_key.to_uppercase());

        // Executables static.
        write!(file, "static {exe_ident}: &[&str] = &[").unwrap();
        for exe in &entry.executables {
            write!(file, "{:?},", exe).unwrap();
        }
        writeln!(file, "];").unwrap();

        // Locations static.
        write!(file, "static {loc_ident}: &[XdgEntryLocation] = &[").unwrap();
        for loc in &entry.locations {
            write!(file, "XdgEntryLocation {{ path: {:?} }},", loc.file).unwrap();
        }
        writeln!(file, "];").unwrap();

        let entry_lit = format!(
            "XdgEntry {{ name: {:?}, executables: {exe_ident}, locations: {loc_ident} }}",
            entry.name,
        );
        map_builder.entry(key.clone(), &entry_lit);
    }

    // Write the PHF map itself.
    writeln!(
        file,
        "static XDB_MAP: phf::Map<&'static str, XdgEntry> = {};",
        map_builder.build()
    )
    .unwrap();

    eprintln!(
        "Generated xdg_db.rs with {} entries at {}",
        deduped.len(),
        dest.display()
    );
}
