use crate::scanners::{Category, Finding, Reason, ScanContext, Scanner};
use crate::util::compute_size;
use std::collections::HashSet;
use std::path::{Path, PathBuf};

const DEFAULT_ROOTS: &[&str] = &["/boot", "/etc", "/opt", "/usr", "/var"];

// Directories we never descend into — their contents are dynamically managed by
// system tools (update-ca-trust, pacman-key, fc-cache, update-mime-database,
// systemctl enable, etc.) and are never owned by pacman. Pruned at the directory
// level so walkdir never enters them at all.
const SKIP_DIR_PREFIXES: &[&str] = &[
    // Package state, caches, logs.
    "/var/cache",
    "/var/lib",
    "/var/log",

    // Kernel/firmware blobs installed by makepkg hooks (not tracked).
    "/usr/lib/modules",
    "/usr/lib/firmware",

    // CA certificate stores — symlinks generated by update-ca-trust on every
    // ca-certificates-mozilla update.
    "/etc/ca-certificates",
    "/etc/ssl/certs",

    // Pacman keyring — managed by pacman-key, not the package db.
    "/etc/pacman.d/gnupg",

    // Fontconfig — symlinks created/removed by font package post-install hooks.
    "/etc/fonts/conf.d",

    // MIME database — regenerated by update-mime-database from owned source files.
    "/usr/share/mime",

    // systemd units — .wants/, .requires/ etc. are populated by `systemctl enable`.
    // Custom units placed here by the user are legitimately outside pacman's scope.
    "/etc/systemd/system",
    "/etc/systemd/user",

    // XML catalogs — regenerated by xmlcatmgr.
    "/etc/xml",

    // X11 config snippets — written by localectl and similar tools.
    "/etc/X11/xorg.conf.d",
];

// File extensions that are pacman-managed conflict markers. NEVER report these
// as orphans: they're created by pacman itself during package updates to preserve
// user customizations (.pacnew = new version, user keeps old; .pacsave = removed
// file with backup flag; .pacorig = legacy variant).
const PACMAN_MARKER_EXTS: &[&str] = &["pacnew", "pacsave", "pacorig"];

/// Lostfiles-style scanner: walks filesystem roots and finds paths not owned by any package.
/// Only used in `pacrid sweep` — too slow for the hook path.
pub struct PacmanOrphanScanner {
    pub roots: Vec<PathBuf>,
}

impl Default for PacmanOrphanScanner {
    fn default() -> Self {
        Self {
            roots: DEFAULT_ROOTS.iter().map(PathBuf::from).collect(),
        }
    }
}

impl Scanner for PacmanOrphanScanner {
    fn name(&self) -> &'static str {
        "pacman_orphan"
    }

    fn scan(&self, ctx: &ScanContext) -> anyhow::Result<Vec<Finding>> {
        assert!(!self.roots.is_empty(), "roots must not be empty");

        let owned = ctx.pacman_db.owned_paths();
        let excludes = load_excludes();
        let mut findings = Vec::new();

        for root in &self.roots {
            if !root.exists() {
                continue;
            }
            walk_root(root, owned, &excludes, ctx, &mut findings);
        }

        Ok(findings)
    }
}

fn walk_root(
    root: &Path,
    owned: &HashSet<PathBuf>,
    excludes: &[glob::Pattern],
    ctx: &ScanContext,
    findings: &mut Vec<Finding>,
) {
    // filter_entry prunes entire directory subtrees when it returns false for a directory.
    // This avoids descending into large uninteresting trees (var/cache, var/lib, etc.)
    // without stat'ing millions of files.
    let walker = walkdir::WalkDir::new(root)
        .follow_links(false)
        .into_iter()
        .filter_entry(|e| {
            if !e.file_type().is_dir() {
                return true; // file-level exclusions handled in the main loop
            }
            let path = e.path();
            // Prune hard-coded directory roots that are never useful.
            if SKIP_DIR_PREFIXES.iter().any(|prefix| path.starts_with(prefix)) {
                return false;
            }
            // Prune directories matching user glob patterns.
            let path_str = path.to_string_lossy();
            if excludes.iter().any(|p| p.matches(&path_str)) {
                return false;
            }
            // Prune directories explicitly ignored in config.
            if ctx.config.ignore.paths.contains(&path.to_path_buf()) {
                return false;
            }
            true
        });

    for entry in walker.filter_map(std::result::Result::ok) {
        let path = entry.path();

        if entry.file_type().is_dir() {
            continue; // never report directories as findings
        }

        if owned.contains(path) {
            continue;
        }

        // Skip pacman's own conflict markers — these are created by pacman itself
        // during package updates and need user action, not deletion.
        if let Some(ext) = path.extension().and_then(|e| e.to_str()) {
            if PACMAN_MARKER_EXTS.contains(&ext) {
                continue;
            }
        }

        let path_str = path.to_string_lossy();
        if excludes.iter().any(|p| p.matches(&path_str)) {
            continue;
        }

        if ctx.config.ignore.paths.contains(&path.to_path_buf()) {
            continue;
        }

        let size_bytes = compute_size(path);
        let confidence = if path.starts_with("/etc/") {
            crate::scanners::Confidence::Medium
        } else {
            crate::scanners::Confidence::Low
        };

        findings.push(Finding {
            path: path.to_path_buf(),
            size_bytes,
            package: String::new(),
            confidence,
            reasons: vec![Reason::PacmanOrphan],
            category: Category::SystemOrphan,
            file_count: 0,
        });
    }
}

/// Load exclude patterns from vendored defaults and user overrides.
fn load_excludes() -> Vec<glob::Pattern> {
    // Common /etc files that are always legitimately unowned (user-generated or system-managed).
    // Note: large directory trees like /var/cache, /var/lib, /var/log are handled by
    // SKIP_DIR_PREFIXES (directory-level pruning) rather than glob patterns.
    let default_patterns = [
        // System config files always edited in place or auto-generated.
        "/etc/.updated",
        "/etc/.pwd.lock",
        "/etc/adjtime",
        "/etc/crypttab",
        "/etc/fstab",
        "/etc/group",
        "/etc/group-",
        "/etc/gshadow",
        "/etc/gshadow-",
        "/etc/hostname",
        "/etc/hosts",
        "/etc/ld.so.cache",
        "/etc/localtime",
        "/etc/locale.conf",
        "/etc/locale.gen",
        "/etc/machine-id",
        "/etc/mkinitcpio.conf",
        "/etc/mkinitcpio.d/*",
        "/etc/modules-load.d/*.conf",
        "/etc/motd",
        "/etc/mtab",
        "/etc/passwd",
        "/etc/passwd-",
        "/etc/resolv.conf",
        "/etc/shadow",
        "/etc/shadow-",
        "/etc/shells",
        "/etc/ssh/ssh_host_*",
        "/etc/subgid",
        "/etc/subuid",
        "/etc/sysctl.d/*.conf",
        "/etc/systemd/network/*",
        "/etc/vconsole.conf",

        // Generated cache files scattered through /usr — regenerated by hooks.
        "/usr/share/info/dir",
        "/usr/share/applications/mimeinfo.cache",
        "/usr/share/glib-2.0/schemas/gschemas.compiled",
        "/usr/share/icons/*/icon-theme.cache",
        "/usr/share/icons/**/icon-theme.cache",
        "/usr/lib/locale/locale-archive",
    ];

    let mut patterns: Vec<glob::Pattern> = default_patterns
        .iter()
        .filter_map(|s| glob::Pattern::new(s).ok())
        .collect();

    // User overrides from /etc/pacrid/excludes.d/*.conf
    let excludes_dir = Path::new("/etc/pacrid/excludes.d");
    if excludes_dir.is_dir() {
        if let Ok(entries) = std::fs::read_dir(excludes_dir) {
            for entry in entries.filter_map(std::result::Result::ok) {
                let path = entry.path();
                if path.extension().and_then(|e| e.to_str()) == Some("conf") {
                    if let Ok(content) = std::fs::read_to_string(&path) {
                        for line in content.lines() {
                            let line = line.trim();
                            if line.is_empty() || line.starts_with('#') {
                                continue;
                            }
                            if let Ok(p) = glob::Pattern::new(line) {
                                patterns.push(p);
                            }
                        }
                    }
                }
            }
        }
    }

    patterns
}
