use crate::scanners::{Category, Finding, Reason, ScanContext, Scanner};
use crate::util::compute_size;
use std::collections::HashSet;
use std::path::{Path, PathBuf};

const DEFAULT_ROOTS: &[&str] = &["/boot", "/etc", "/opt", "/usr", "/var"];

// Directories we never descend into — their contents are dynamically managed by
// system tools (update-ca-trust, pacman-key, fc-cache, update-mime-database,
// systemctl enable, etc.) and are never owned by pacman. Pruned at the directory
// level so walkdir never enters them at all.
const SKIP_DIR_PREFIXES: &[&str] = &[
    // Package state, caches, logs.
    "/var/cache",
    "/var/lib",
    "/var/log",
    // Kernel/firmware blobs installed by makepkg hooks (not tracked).
    "/usr/lib/modules",
    "/usr/lib/firmware",
    // CA certificate stores — symlinks generated by update-ca-trust on every
    // ca-certificates-mozilla update.
    "/etc/ca-certificates",
    "/etc/ssl/certs",
    // Pacman keyring — managed by pacman-key, not the package db.
    "/etc/pacman.d/gnupg",
    // Fontconfig — symlinks created/removed by font package post-install hooks.
    "/etc/fonts/conf.d",
    // MIME database — regenerated by update-mime-database from owned source files.
    "/usr/share/mime",
    // systemd units — .wants/, .requires/ etc. are populated by `systemctl enable`.
    // Custom units placed here by the user are legitimately outside pacman's scope.
    "/etc/systemd/system",
    "/etc/systemd/user",
    // XML catalogs — regenerated by xmlcatmgr.
    "/etc/xml",
    // X11 config snippets — written by localectl and similar tools.
    "/etc/X11/xorg.conf.d",
];

// File extensions that are pacman-managed conflict markers. NEVER report these
// as orphans: they're created by pacman itself during package updates to preserve
// user customizations (.pacnew = new version, user keeps old; .pacsave = removed
// file with backup flag; .pacorig = legacy variant).
const PACMAN_MARKER_EXTS: &[&str] = &["pacnew", "pacsave", "pacorig"];

/// Lostfiles-style scanner: walks filesystem roots and finds paths not owned by any package.
/// Only used in `pacrid sweep` — too slow for the hook path.
pub struct PacmanOrphanScanner {
    pub roots: Vec<PathBuf>,
}

impl Default for PacmanOrphanScanner {
    fn default() -> Self {
        Self {
            roots: DEFAULT_ROOTS.iter().map(PathBuf::from).collect(),
        }
    }
}

impl Scanner for PacmanOrphanScanner {
    fn name(&self) -> &'static str {
        "pacman_orphan"
    }

    fn scan(&self, ctx: &ScanContext) -> anyhow::Result<Vec<Finding>> {
        assert!(!self.roots.is_empty(), "roots must not be empty");

        let owned = ctx.pacman_db.owned_paths();
        let excludes = load_excludes();
        let mut findings = Vec::new();

        for root in &self.roots {
            if !root.exists() {
                continue;
            }
            walk_root(root, owned, &excludes, ctx, &mut findings);
        }

        Ok(findings)
    }
}

fn walk_root(
    root: &Path,
    owned: &HashSet<PathBuf>,
    excludes: &[glob::Pattern],
    ctx: &ScanContext,
    findings: &mut Vec<Finding>,
) {
    let walker = walkdir::WalkDir::new(root)
        .follow_links(false)
        .into_iter()
        .filter_entry(|e| !should_prune_dir(e, excludes, ctx));

    for entry in walker.filter_map(std::result::Result::ok) {
        if entry.file_type().is_dir() {
            continue; // never report directories as findings
        }
        let path = entry.path();
        if file_is_skippable(path, owned, excludes, ctx) {
            continue;
        }
        findings.push(make_orphan_finding(path));
    }
}

/// True when this directory should not be descended into.
/// `filter_entry` returning false on a dir prunes the entire subtree, which is
/// the only way to avoid stat'ing millions of files under var/cache, var/lib, etc.
fn should_prune_dir(
    entry: &walkdir::DirEntry,
    excludes: &[glob::Pattern],
    ctx: &ScanContext,
) -> bool {
    if !entry.file_type().is_dir() {
        return false; // file-level exclusions handled in the main loop
    }
    let path = entry.path();
    if SKIP_DIR_PREFIXES
        .iter()
        .any(|prefix| path.starts_with(prefix))
    {
        return true;
    }
    let path_str = path.to_string_lossy();
    if excludes.iter().any(|p| p.matches(&path_str)) {
        return true;
    }
    if ctx.config.ignore.paths.contains(&path.to_path_buf()) {
        return true;
    }
    false
}

/// True when the file should not be reported (owned by a package, a pacman
/// conflict marker, matching a user exclude, or in the ignore list).
fn file_is_skippable(
    path: &Path,
    owned: &HashSet<PathBuf>,
    excludes: &[glob::Pattern],
    ctx: &ScanContext,
) -> bool {
    if owned.contains(path) {
        return true;
    }
    if let Some(ext) = path.extension().and_then(|e| e.to_str()) {
        if PACMAN_MARKER_EXTS.contains(&ext) {
            return true;
        }
    }
    let path_str = path.to_string_lossy();
    if excludes.iter().any(|p| p.matches(&path_str)) {
        return true;
    }
    if ctx.config.ignore.paths.contains(&path.to_path_buf()) {
        return true;
    }
    false
}

fn make_orphan_finding(path: &Path) -> Finding {
    let size_bytes = compute_size(path);
    let confidence = if path.starts_with("/etc/") {
        crate::scanners::Confidence::Medium
    } else {
        crate::scanners::Confidence::Low
    };
    Finding {
        path: path.to_path_buf(),
        size_bytes,
        package: String::new(),
        confidence,
        reasons: vec![Reason::PacmanOrphan],
        category: Category::SystemOrphan,
        file_count: 0,
    }
}

/// Common /etc files that are always legitimately unowned (user-generated or
/// system-managed). Large directory trees like /var/cache, /var/lib, /var/log
/// are handled by `SKIP_DIR_PREFIXES` — these are individual files only.
const DEFAULT_EXCLUDE_PATTERNS: &[&str] = &[
    // System config files always edited in place or auto-generated.
    "/etc/.updated",
    "/etc/.pwd.lock",
    "/etc/adjtime",
    "/etc/crypttab",
    "/etc/fstab",
    "/etc/group",
    "/etc/group-",
    "/etc/gshadow",
    "/etc/gshadow-",
    "/etc/hostname",
    "/etc/hosts",
    "/etc/ld.so.cache",
    "/etc/localtime",
    "/etc/locale.conf",
    "/etc/locale.gen",
    "/etc/machine-id",
    "/etc/mkinitcpio.conf",
    "/etc/mkinitcpio.d/*",
    "/etc/modules-load.d/*.conf",
    "/etc/motd",
    "/etc/mtab",
    "/etc/passwd",
    "/etc/passwd-",
    "/etc/resolv.conf",
    "/etc/shadow",
    "/etc/shadow-",
    "/etc/shells",
    "/etc/ssh/ssh_host_*",
    "/etc/subgid",
    "/etc/subuid",
    "/etc/sysctl.d/*.conf",
    "/etc/systemd/network/*",
    "/etc/vconsole.conf",
    // Generated cache files scattered through /usr — regenerated by hooks.
    "/usr/share/info/dir",
    "/usr/share/applications/mimeinfo.cache",
    "/usr/share/glib-2.0/schemas/gschemas.compiled",
    "/usr/share/icons/*/icon-theme.cache",
    "/usr/share/icons/**/icon-theme.cache",
    "/usr/lib/locale/locale-archive",
];

const USER_EXCLUDES_DIR: &str = "/etc/pacrid/excludes.d";

/// Load exclude patterns: vendored defaults plus any user overrides in
/// /etc/pacrid/excludes.d/*.conf.
fn load_excludes() -> Vec<glob::Pattern> {
    let mut patterns: Vec<glob::Pattern> = DEFAULT_EXCLUDE_PATTERNS
        .iter()
        .filter_map(|s| glob::Pattern::new(s).ok())
        .collect();
    append_user_excludes(Path::new(USER_EXCLUDES_DIR), &mut patterns);
    patterns
}

/// Append user-defined glob patterns from `*.conf` files in `dir`.
/// Silently ignores unreadable files or unparseable patterns — exclude lists
/// are advisory, never load-bearing for correctness.
fn append_user_excludes(dir: &Path, out: &mut Vec<glob::Pattern>) {
    if !dir.is_dir() {
        return;
    }
    let Ok(entries) = std::fs::read_dir(dir) else {
        return;
    };
    for entry in entries.filter_map(std::result::Result::ok) {
        let path = entry.path();
        if path.extension().and_then(|e| e.to_str()) != Some("conf") {
            continue;
        }
        let Ok(content) = std::fs::read_to_string(&path) else {
            continue;
        };
        for line in content.lines() {
            let line = line.trim();
            if line.is_empty() || line.starts_with('#') {
                continue;
            }
            if let Ok(p) = glob::Pattern::new(line) {
                out.push(p);
            }
        }
    }
}
